config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :artworks, only: [:index, :new, :create, :show]
  resources :auctions, only: [:index, :new, :create, :show] do
    resources :auction_items, only: [:index, :show, :new, :create] do
      resources :bids, only: [:create, :show]
    end
  end
  resources :bids, only: [:index]
  get 'profile', to: 'pages#profile', as: 'profile'
  post 'profile', to: 'pages#update', as: 'update_photo'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'my_auctions', to: 'pages#my_auctions', as: 'my_auctions'
  resources :auction_items, only: [] do
    member do
      patch 'finish_bid'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bid.rb
class Bid < ApplicationRecord
  validates :price, numericality: { less_than: 10000000 }

  belongs_to :user
  #belongs_to :auction
  belongs_to :auction_item
  validates :auction_item_id, uniqueness: { scope: :user_id,
  message: "You can only make one bid" }
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  def index
    @bids = Bid.where(user_id: params[:user_id])
  end

  def create
    @auction = Auction.find(params[:auction_id])
    @auction_item = AuctionItem.find(params[:auction_item_id])
    @bid = Bid.new(bids_params)
    @bid.user = current_user
    @bid.auction_item_id = params[:auction_item_id]


    if @bid.save
      BidroomChannel.broadcast_to(
        @auction_item,
        render_to_string(partial: "shared/bid", locals: { bid: @bid })
      )
      head :ok
      #redirect_to auction_auction_item_path(@auction, @auction_item)
    else
      #redirect_to auction_auction_item_path(@auction_item), notice: "You can only place one bid"
      render 'auction_items/show'
    end

  end

  private

  def bids_params
    params.require(:bid).permit(:price, :user_id, :auction_item_id)
  end
end

app/views/bids/index.html.erb
<h2>My Bidding Activity</h2>
<h3>Bids#index</h3>
<div class="row">
    <% @bids.each do |bid|%>
      <div class="col-sm-4">
        <div class="card-product">
          <b class="card-date-byline"><%= bid.auction_item.auction.date %></b>
          <%= link_to bid_path (bid.id) do %>
            <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
          <% end %>
          <div class="card-product-infos">
            <span><h6><i class="fas fa-map-marker-alt"></i> <%= auction.address %></h6>&nbsp;
              <p class="byline"> by <%= bid.auction_item.auction.user.first_name %> <%= auction.user.last_name %></p>
            </span>
            <h4><%= auction.title %> </h4>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>