config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :artworks, only: [:index, :new, :create, :show]
  resources :auctions, only: [:index, :new, :create, :show] do
    resources :auction_items, only: [:index, :show, :new, :create] do
      resources :bids, only: [:create, :show]
    end
  end
  resources :bids, only: [:index]
  get 'profile', to: 'pages#profile', as: 'profile'
  post 'profile', to: 'pages#update', as: 'update_photo'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'my_auctions', to: 'pages#my_auctions', as: 'my_auctions'
  resources :auction_items, only: [] do
    member do
      patch 'finish_bid'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/auction.rb
class Auction < ApplicationRecord
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :description, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  # validates :photo, presence: true
  has_many :auction_items, dependent: :destroy
  has_many :artworks, through: :auction_items
  #has_many :bids, through: :auction_items
  belongs_to :user
  has_one_attached :photo

  # DATEPICKER_JS = {
  #   format: 'YYYY-MM-DD HH:mm',
  #   showTodayButton: true,
  #   icons: {
  #     time: 'fa fa-clock-o',
  #     date: 'fa fa-calendar',
  #     up: 'fa fa-arrow-up',
  #     down: 'fa fa-arrow-down',
  #     previous: 'fa fa-chevron-left',
  #     next: 'fa fa-chevron-right',
  #     today: 'fa fa-calendar-check-o',
  #     clear: 'fa fa-delete',
  #     close: 'fa fa-times'
  #   }
  # }
end

app/controllers/auctions_controller.rb
require 'rqrcode'

class AuctionsController < ApplicationController
  protect_from_forgery except: [:show]
  before_action :enter_auctions, only: [:show]

  def index
    @auctions = Auction.all
  end

  def show

    @auction = Auction.includes(auction_items: :artwork).find(params[:id])
    @user = @auction.user
    @url = "https://www.artcollective.live/" + auction_path(@auction)
    @qr_code = RQRCode::QRCode.new(@url)
    @svg = @qr_code.as_svg(
      offset: 0,
      color: '0c0e1e',
      shape_rendering: 'crispEdges',
      standalone: true
    )
    @artworks = @user.artworks_as_artist

    @artworks.each do |artwork|
      if !artwork.auction_items.exists?
        auction_item = AuctionItem.new
        auction_item.auction = @auction
        auction_item.artwork = artwork
        auction_item.save
      end
    end
    @auction_items = @auction.auction_items
    @auction_item = AuctionItem.new
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(auction_params)
    @auction.user = current_user
    if @auction.save
      # where am i redirecting to?
      redirect_to auction_path(@auction), notice: "Your auction was successfully listed!"
    else
      render :new
    end
  end

  # def edit
  #   @auction = Auction.find(params[:id])
  # end

  # def update
  #   @auction = Auction.find(params[:id])
  #   @auction.update(auction_params)
  #   # where am i redirecting to?
  #   redirect_to my_auctions_path(current_user), notice: "Your auction was successfully updated!"
  # end

  # def destroy
  #   @auction = Auction.find(params[:id])
  #   @auction.destroy
  #   # where am i redirecting to?
  #   redirect_to auction_path(current_user), notice: "Your auction was successfully removed."
  # end

  private

  def auction_params
    params.require(:auction).permit(:title, :description, :address, :user_id, :date, :status, :start_time, :end_time, :photo)
  end



  def enter_auctions
      #create a new QR Code (rQRCode assumes string data)
    qrcode = RQRCode::QRCode.new(auction_path)
    @qrcode_html = qrcode.as_html
  end

end

app/views/auctions/index.html.erb
<div class="container my-5">

  <div class="row">
  <h2>Upcoming auctions</h2>
    <% @auctions.each do |auction|%>
      <div class="col-sm-4">
        <div class="card-product">
          <b class="card-date-byline"><%= auction.end_time.to_formatted_s(:short) %></b>
          <%= link_to auction_path (auction.id) do %>
            <% if auction.photo.present? %>
              <%= cl_image_tag auction.photo.key, class: "w-100" %>
            <% else %>
              <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
            <% end %>
          <% end %>
          <div class="card-product-infos">
            <span><h6><i class="fas fa-map-marker-alt"></i> <%= auction.address %></h6>&nbsp;
              <p class="byline"> by <%= auction.user.first_name %> <%= auction.user.last_name %></p>
            </span>
            <h4><%= auction.title %> </h4>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/auctions/new.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2>Create an Auction</h2>
      <%= render "shared/add_auction" %>
    </div>
  </div>
</div>

app/views/auctions/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <div class="me-3">
        <h6><%= @auction.date.to_formatted_s(:long) %></h6>
        <h3><%= @auction.title %></h3>
        <p> <%= @auction.description %></p>
        <p> <%= @auction.start_time.strftime("%I:%M %p") %> - <%= @auction.end_time.strftime("%I:%M %p") %></p>
        <p><%= render "shared/counter", auction: @auction %></p>

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <i class="fas fa-qrcode"></i> Scan QR code
        </button>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Sign up for the Art Collective</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body text-center">
                <p>Sign up by following the QR code link below.</p>
                <%= @svg.html_safe %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        <!-- End of modal -->

        <div class="bids my-5">
          <table class="table" data-bidding-target="content">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Bidder</th>
                <th scope="col">Artwork</th>
                <th scope="col">Bid Time</th>
              </tr>
            </thead>
            <tbody>
              <% @auction_items.each do |auction_item| %>
                <% auction_item.bids.each do |bid| %>
                <tr class="bid-table" id="bid-<%= bid.id %>">
                  <td class= "photo-center"><%= user_photo_bid(bid.user) %></td>
                  <td><%= bid.user.first_name %> <%= bid.user.last_name %></td>
                  <td><%= bid.auction_item.artwork.title %></td>
                  <td> <%= bid.created_at.to_formatted_s(:short) %></td>
                </tr>
                <% end %>
              <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-md-6">
      <% @auction_items.each do |item| %>
        <div class="card-product-list d-flex">
          <div class="col-sm-12 col-md-6 pe-3">
            <% if item.artwork.photo.present? %>
              <%= cl_image_tag item.artwork.photo.key, crop: :scale, class: "w-100" %>
            <% else %>
              <%= cl_image_tag item.artwork.photo.key.to_s, crop: :scale, class: "w-100" %>
            <% end %>
          </div>
          <div class="col-sm-12 col-md-6 mt-3">
            <div class="card-product-infos-list">
              <h6><i class="fas fa-map-marker-alt"></i> <%= @auction.address %></h6>
              <h4><%= item.artwork.title %></h4>
              <%= link_to auction_auction_item_path(@auction, item), class: "btn btn-primary" do %>
             Join auction <i class="fas fa-arrow-right"></i>
              <% end %>
            </div>
          </div>
        </div>
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/auctions/show.js.erb
document.write("<%= j(render(:partial => 'counter', :locals => {:counter => @counter}).html_safe) %>");