config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :artworks, only: [:index, :new, :create, :show]
  resources :auctions, only: [:index, :new, :create, :show] do
    resources :auction_items, only: [:index, :show, :new, :create] do
      resources :bids, only: [:create, :show]
    end
  end
  resources :bids, only: [:index]
  get 'profile', to: 'pages#profile', as: 'profile'
  post 'profile', to: 'pages#update', as: 'update_photo'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'my_auctions', to: 'pages#my_auctions', as: 'my_auctions'
  resources :auction_items, only: [] do
    member do
      patch 'finish_bid'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_add_artwork.html.erb
<%= simple_form_for @artwork do |f| %>
      <%= f.input :title %>
      <%= f.input :price %>
      <%= f.input :description %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Submit", class: "btn btn-primary w-100" %>
    <% end %>

app/views/shared/_add_auction.html.erb
<%= simple_form_for @auction do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :address %>
      <%= f.input :date %>
      <%= f.input :start_time %>
      <%= f.input :end_time %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Submit", class: "btn btn-primary w-100" %>
    <% end %>

app/views/shared/_bid.html.erb
  <tr class="bid-table" id="bid-<%= bid.id %>">
    <td class= "photo-center"><%= user_photo_bid(bid.user) %></td>
    <td><%= bid.user.first_name %> <%= bid.user.last_name %> </td>
    <td><%= bid.created_at.strftime("%I:%M %p") %></td>
    <td><%= bid.price %>€</td>
  </tr>

app/views/shared/_carousel.html.erb
<div class="row align-items-center">
  <div class="col-12 col-md-6 paint-background">
    <h6>Find your masterpiece</h6>
    <h2>Discover the<br>
      next Mona Lisa</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sodales nulla elementum eget.</p>
  </div>
  <div class="col-12 col-md-6 right-half">
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="https://res.cloudinary.com/dmty5wfjh/image/upload/v1645563638/pexels-steve-johnson-3189607_wf13kl.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="https://image.jimcdn.com/app/cms/image/transf/none/path/sa6549607c78f5c11/image/i31f41beba573734f/version/1500387364/unmissable-paintings-in-europe-the-scream-by-edvard-munch.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="https://res.cloudinary.com/dmty5wfjh/image/upload/v1645563638/pexels-steve-johnson-3189607_wf13kl.jpg" class="d-block w-100" alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>

app/views/shared/_counter.html.erb
<h5>Time remaining:</h5>
<!-- Display the countdown timer in an element -->
<p id="demo"></p>
<script>
 // Set the date we're counting down to
var countDownDate = new Date("<%= auction.end_time %>".replace(/-/g, "/")).getTime();
// Update the count down every 1 second
var x = setInterval(function() {
// Get todays date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Output the result in an element with id="demo"
  if (days > 0) {
  document.getElementById("demo").innerHTML = days + "d " + hours + "h "
  + minutes + "m " + seconds + "s ";
  }
  else {
  document.getElementById("demo").innerHTML = hours + "h "
  + minutes + "m " + seconds + "s ";
  }

  // If the count down is over, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "The auction has ended!";

  }
}, 1000);
</script>

app/views/shared/_counter_items.html.erb
<h5>Time remaining:</h5>
<!-- Display the countdown timer in an element -->
<span style="font-family: Tahoma, Geneva, sans-serif;" id="demo" data-controller="countdown" data-countdown-end-value="<%= auction_item.auction.end_time %>" data-countdown-url-value="<%= finish_bid_auction_item_url(auction_item) %>" data-countdown-info-value="<%= auction_item.artwork.to_json %>" data-countdown-buyer-value="<%= auction_item.artwork.buyer.to_json %>"></span>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row my-5">
      <div class="col-sm-12">
            <%= image_tag "ac.png", class: :small %>

      </div>
    </div>
    <div class="row my-3">
      <div class="col-sm-3">
        <h6>Popular Auctions</h6>
        <br>
        <p><a href="#">Frida Kahlo oil paintings on canvas</a></p>
        <p><a href="#">Georgia O’Keeffe: Art, Image, Style</a></p>
        <p> <a href="#">The Ecstasy of Code by Alan Paint</a></p>
        <br>
      </div>
      <div class="col-sm-3">
        <h6>Sell your art</h6>
        <br>
        <p><%= link_to "List artwork for sale", new_artwork_path %></p>
        <p><%= link_to "Create an auction", new_auction_path %></p>
        <br>
      </div>
      <div class="col-sm-3">
        <h6>Art Collective</h6>
        <br>
        <p><a href="#">About us</a></p>
        <p><%= link_to "Update my profile", edit_user_registration_path %></p>
        <br>
      </div>
      <div class="col-sm-3">
        <h6>Support</h6>
        <br>
        <p><a href="#">FAQs</a></p>
        <p><a href="#">Contact us</a></p>
        <br>
      </div>
      <div class="row my-3">
        <div class="col-sm-3">
          <div class="footer-links">
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
          </div>
        </div>
      </div>
        <div class="row my-5">
          <div class="col-sm-6">
            <p class="footer-white">© 2022 ART COLLECTIVE - ALL RIGHTS RESERVED.</p>
          </div>
          <div class="col-sm-2">
            <p class="byline"><a href="#">PRIVACY POLICY</a></p>
          </div>
          <div class="col-sm-2">
            <p class="byline"><a href="#">COOKIE POLICY</a></p>
          </div>
          <div class="col-sm-2">
            <p class="byline"><a href="#">TERMS & CONDITIONS</a></p>
          </div>
        </div>
      </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon py-5">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand d-flex" do %>
      <%= image_tag "ac-mona.png" %>
      <h3 class="logo-text">Art Collective</h3>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Auctions", auctions_path, class: "nav-link" %>
          </li>
          <li class="nav-item d-block d-sm-none">
            <%= link_to "My Profile", profile_path, class: "nav-link" %>
          </li>
          <li class="nav-item d-block d-sm-none">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= user_photo(current_user) %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Auctions", auctions_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
        <%= simple_form_for :search, url: root_path, method: :get do |f| %>
      <div class="search-form-control form-group">
        <input class="form-control string required" type="text" name="search[query]" id="search_query" />
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i> Search
        </button>
        </div>
        <% end %>

app/views/shared/_user_profile.html.erb
<%= simple_form_for(user_registration_path) do |f| %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Change profile photo", class: "btn btn-primary w-100" %>
<% end %>

app/views/shared/_win.html.erb
<p>You win!</p>