config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :artworks, only: [:index, :new, :create, :show]
  resources :auctions, only: [:index, :new, :create, :show] do
    resources :auction_items, only: [:index, :show, :new, :create] do
      resources :bids, only: [:create, :show]
    end
  end
  resources :bids, only: [:index]
  get 'profile', to: 'pages#profile', as: 'profile'
  post 'profile', to: 'pages#update', as: 'update_photo'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'my_auctions', to: 'pages#my_auctions', as: 'my_auctions'
  resources :auction_items, only: [] do
    member do
      patch 'finish_bid'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/enter_auctions.html.erb
<h3>Enter the auction below by scanning the QR Code</h3>

<%# move to CSS file!!
<style>
  table {
  border-width: 0;
  border-style: none;
  border-color: #0000ff;
  border-collapse: collapse;
  }

  td {
  border-left: solid 10px #000;
  padding: 0;
  margin: 0;
  width: 0px;
  height: 10px;
  }

  td.black { border-color: #000; }
  td.white { border-color: #fff; }
</style>
%>

#now embed the qrcode html using the "raw" ruby viewhelper
<%= raw @qrcode_html %>

app/views/pages/home.html.erb
<div class="home-search text-center pt-3 pb-5">
  <h2 class="p-1">Discover masterpieces<br>
    from artists across the globe.</h2>
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto my-5">
        <%= link_to "JOIN AN AUCTION", auctions_path, class: "btn btn-primary btn-lg w-50 mb-4" %>
        <%#
        <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get">
          <div class="search-form-control form-group">
            <input class="form-control string required" type="text" name="search[query]" id="search_query">
            <button name="button" type="submit" class="btn btn-flat">
              <i class="fas fa-search"></i></button> %>
      </div>
    </form>
  </div>
</div>
</div>
</div>
<div class="container">
  <div class="d-flex align-items-center my-5">
    <div class="col-sm-12 col-md-6 paintstroke d-none d-lg-block mb-5">
      <h6>LIVE AUCTIONS</h6>
      <h2>Find the next Mona Lisa</h2>
      <p>Purchase rare, one of a kind artworks by bidding,
        acquiring, and selling your own artwork all through our online auctions.</p>
    </div>
    <div class="col-sm-12 col-md-6 d-flex d-none d-lg-block justify-content-between">
      <div>
        <%= image_tag "background-img.jpg", class: "img-wide" %>
      </div>
    </div>
    <div class="row d-lg-none">
      <div class="col-sm-12 paintstroke mb-5">
        <h6>ARTIST SERIES</h6>
        <h2>Find the next Mona Lisa</h2>
        <p>Purchase rare, one of a kind artworks by bidding,
          acquiring, and selling your own artwork all through our online auctions.</p>
      </div>
      <div class="col-sm-12">
        <%= image_tag "homepage-image-1.jpg", class: "img-wide-mobile" %>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid py-5 focus">
  <div class="container">
    <div class="row">
      <div class="col-md-12 my-5 text-center">
        <h2>Bid, Buy and Sell</h2>
        <p>Find, buy and sell collection artwork from leading artists, auction houses
          and nonprofit organizations from across the world – all from one online marketplace.</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/my_auctions.html.erb
<h1>Welcome to your auctions page, <%= @user.first_name %></h1>

<a href=<%= new_auction_path %>>Create a new artwork</a>

<h2>All of your auctions</h2>

<%# Will need some work below to show the auction activity %>

<% @user.artworks_as_artist.each do |artwork| %>
  <p><%= artwork.title%> -- <%= artwork.price %> <a href=<%= artwork_path(artwork) %>>See this artwork</a></p>
  <% if artwork.photo.present? %>
    <%= cl_image_tag artwork.photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>
<% end %>

<h2>All your artwork for auction</h2>

<% @user.artworks_as_artist.each do |artwork| %>
  <p><%= artwork.title%> -- <%= artwork.price %> <a href=<%= artwork_path(artwork) %>>See this artwork</a></p>
  <% if artwork.photo.present? %>
    <%= cl_image_tag artwork.photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>
<% end %>

<h2>Artwork you've purchased</h2>

  <% @user.artworks_as_buyer.each do |artwork| %>
  <p><%= artwork.title%> -- <%= artwork.price %><a href=<%= artwork_path(artwork) %>>See this artwork</a></p>
  <% if artwork.photo.present? %>
    <%= cl_image_tag artwork.photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>
<% end %>

<h2>Artwork you've sold</h2>

<% @user.artworks_as_artist.each do |artwork| %>
  <% if artwork.buyer_id != current_user.id %>
    <p><%= artwork.title%> -- <%= artwork.price %><a href=<%= artwork_path(artwork) %>>See this artwork</a></p>
    <% if artwork.photo.present? %>
      <%= cl_image_tag artwork.photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  <% end %>
<% end %>

app/views/pages/profile.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-8 ">
      <h4>My Dashboard</h4>
      <hr>
      <div class="row">
      <div class="col-md-4 mb-3">
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-primary w-100" data-bs-toggle="modal" data-bs-target="#exampleModal">
            <i class="fas fa-user-circle"></i><br>
            Update profile photo
          </button>
          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Upload a new profile photo below</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                  <%= profile_photo(@user)%>
                  <%= render "shared/user_profile", user: @user %>
                  <br>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
          <!-- End of modal -->
        </div>
        <div class="col-md-4 mb-3">
          <%= link_to new_artwork_path, class: "btn btn-primary w-100" do %>
            <i class="fas fa-money-bill"></i><br>
            List an artwork
          <% end %>
        </div>
        <div class="col-md-4 mb-3"><%= link_to new_auction_path, class: "btn btn-primary w-100" do %>
            <i class="fas fa-plus-circle"></i><br>
            Create an auction
          <% end %></div>

        <div class="col-md-12">
          <h4 class="mb-3">My Bids</h4>
          <table class="table" data-bidding-target="content">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Artwork Title</th>
                <th scope="col">Bid Date/Time</th>
                <th scope="col">Bid Amount</th>
              </tr>
            </thead>
            <tbody>
              <% current_user.bids.each do |bid| %>
                <tr class="bid-table" id="bid-<%= bid.id %>">
                  <td class= "photo-center"><%= user_photo_bid(bid.user) %></td>
                  <td><%= bid.auction_item.artwork.title %></td>
                  <td> <%= bid.created_at.to_formatted_s(:short) %></td>
                  <td><%= bid.price %>€</td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <h4>My Artworks</h4>
      <hr>
      <% @user.artworks_as_buyer.each do |artwork| %>
        <div class="card-product-list d-flex">
          <div class="col-sm-12 col-md-6 mb-3 pe-3">
            <% if artwork.photo.present? %>
              <%= cl_image_tag artwork.photo.key %>
            <% else %>
            <% end %>
          </div>
          <div class="col-sm-12 col-md-6 mt-2">
            <div class="card-product-infos-list">
              <h5><%= artwork.title %></h5>
              <p><%= artwork.price %> €</p>
            </div>
          </div>
        </div>
      <% end %>
      <br>
    </div>
  </div>
</div>